# https://docs.docker.com/compose/django/
version: "3.9"

services:
  db:
    image: library/postgres:13
    env_file:
      - .env.dev
    # Ports is only open for dev
    ports:
    - 5432:5432
    volumes:
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - codenforce:/var/lib/postgresql/data

  web:
    build: services/web
    env_file:
      - .env.dev
    volumes:
    - ./services/web/:/app
    ports:
    - "8000:8000"
    depends_on:
      - db

volumes:
  codenforce:
