# Creates a merged pure.css file
# css didn't come out as I expected it
# Todo: Delete file, but generalize this script and put it away somewhere for future use.

from os import path, listdir

HERE = path.dirname(path.realpath(__file__))
ROOT = path.split(HERE)[0]
SRC = path.join(
    ROOT, "services", "web", "codenforce", "static", "sources", "pure", "src"
)
merged_filename = path.join(
    ROOT, "services", "web", "codenforce", "static", "css", "_pure.css"
)
with open(merged_filename, "w") as merged_file:
    merged_file.write(
        f"/* This file was generated by {__file__}.\n"
        f"It is a combination of all files from the 'pure' css library.\n"
        f"The css here represents a starting point for the resulting css,"
        f"\n but changes made are not reflected by this code. */"
    )
    for folder in listdir(SRC):
        css_dir = path.join(SRC, folder, "css")
        files = [path.join(css_dir, file) for file in listdir(css_dir)]
        for file in files:
            with open(file, "r") as pure_file:
                [merged_file.write(line) for line in pure_file]
